-- dshstudio/lang.lua
--
-- Language-specific behaviour for the four target languages.
--
-- The language servers (clangd/pyright/fortls) own completion and navigation;
-- this module owns everything they do not: correct-format detection, indentation
-- that matches each language's convention, the build/run loop, and the project
-- bootstrap files that make a language server useful on a fresh checkout.

local M = {}

local uv = vim.uv or vim.loop

local function util()
  local ok, mod = pcall(require, 'dshstudio.util')
  if ok then return mod end
  return {
    notify = function(m, l) vim.notify(m, l, { title = 'DSH Studio' }) end,
    find_root = function(start, markers)
      local dir = start
      for _ = 1, 12 do
        for _, marker in ipairs(markers) do
          if vim.fn.filereadable(dir .. '/' .. marker) == 1
            or vim.fn.isdirectory(dir .. '/' .. marker) == 1 then
            return dir
          end
        end
        local parent = vim.fn.fnamemodify(dir, ':h')
        if parent == dir or parent == '' then return nil end
        dir = parent
      end
      return nil
    end,
  }
end

local function config()
  local ok, mod = pcall(require, 'dshstudio.config')
  if ok and mod.get then return mod end
  return { get = function(_, default) return default end }
end

-- ---------------------------------------------------------------------------
-- Filetype detection
-- ---------------------------------------------------------------------------

---Fortran source files can be fixed- or free-form, and the compiler decides by
---extension plus build flags. Getting this wrong breaks highlighting and
---indentation, so the extension wins first and a heuristic covers `.f`.
---@param buf integer|nil
function M.fortran_form(buf)
  buf = buf or vim.api.nvim_get_current_buf()
  local name = vim.api.nvim_buf_get_name(buf):lower()
  if name:match('%.f90$') or name:match('%.f95$') or name:match('%.f03$')
    or name:match('%.f08$') or name:match('%.f18$') then
    return 'free'
  end
  if name:match('%.f$') or name:match('%.for$') or name:match('%.ftn$') then
    -- Older extensions are usually fixed form, but a long free-form line or a
    -- `&` continuation is a strong signal otherwise.
    local lines = vim.api.nvim_buf_get_lines(buf, 0, math.min(200, vim.api.nvim_buf_line_count(buf)), false)
    local long_lines = 0
    for _, line in ipairs(lines) do
      if #line > 72 then long_lines = long_lines + 1 end
    end
    if long_lines > 3 then return 'free' end
    return 'fixed'
  end
  -- `.F90`, `.F`, or a file with no recognised extension: decide from content.
  local lines = vim.api.nvim_buf_get_lines(buf, 0, math.min(80, vim.api.nvim_buf_line_count(buf)), false)
  for _, line in ipairs(lines) do
    if line:match('^%s*!') then return 'free' end
  end
  return 'fixed'
end

---Force the right filetype for a buffer, working around old Vim script
---detection that lets `.f` win over `.f90` when both patterns are registered.
function M.fix_fortran_filetype(buf)
  buf = buf or vim.api.nvim_get_current_buf()
  local name = vim.api.nvim_buf_get_name(buf):lower()
  if not name:match('%.f%d*%d$') and not name:match('%.for$') and not name:match('%.ftn$') then
    return
  end
  if vim.bo[buf].filetype ~= 'fortran' then
    vim.bo[buf].filetype = 'fortran'
  end
end

-- ---------------------------------------------------------------------------
-- Project bootstrap helpers
-- ---------------------------------------------------------------------------

---Write a `.clangd` file so clangd resolves headers in unusual layouts.
---Only created on explicit request; never overwrites an existing file.
---@param root string
---@return boolean created
function M.write_clangd_config(root)
  local path = root .. '/.clangd'
  if vim.fn.filereadable(path) == 1 then
    util().notify('.clangd already exists — left untouched', vim.log.levels.INFO)
    return false
  end
  local dirs = config().get('extra_include_dirs') or {}
  local lines = {
    '# Generated by DSH Studio. Adjust or delete freely.',
    'CompileFlags:',
    '  Add:',
  }
  if #dirs == 0 then
    table.insert(lines, '    - -Iinclude')
  else
    for _, dir in ipairs(dirs) do
      table.insert(lines, ('    - -I%s'):format(dir))
    end
  end
  table.insert(lines, 'Diagnostics:')
  table.insert(lines, '  UnusedIncludes: None')
  local fh = io.open(path, 'w')
  if not fh then
    util().notify('could not write ' .. path, vim.log.levels.ERROR)
    return false
  end
  fh:write(table.concat(lines, '\n') .. '\n')
  fh:close()
  util().notify('wrote ' .. path, vim.log.levels.INFO)
  return true
end

---Write a `.fortls` file for Fortran projects without a build system.
---@param root string
---@param include_dirs string[]|nil
---@return boolean created
function M.write_fortls_config(root, include_dirs)
  local path = root .. '/.fortls'
  local lines = {
    '"Generated by DSH Studio. Adjust or delete freely."',
    '{',
    '  "incremental_sync": true,',
    '  "sort_keywords": false,',
    '  "hover_signature": true,',
    '  "use_signature_help": true,',
  }
  include_dirs = include_dirs or config().get('fortran_include_dirs') or {}
  if #include_dirs > 0 then
    local quoted = {}
    for _, dir in ipairs(include_dirs) do
      table.insert(quoted, ('"%s"'):format(dir))
    end
    table.insert(lines, ('  "incl_paths": [%s]'):format(table.concat(quoted, ', ')))
  end
  table.insert(lines, '}')
  local fh = io.open(path, 'w')
  if not fh then
    util().notify('could not write ' .. path, vim.log.levels.ERROR)
    return false
  end
  fh:write(table.concat(lines, '\n') .. '\n')
  fh:close()
  util().notify('wrote ' .. path, vim.log.levels.INFO)
  return true
end

---Detect the build system for a root.
---@param root string
---@return string  'cmake' | 'make' | 'fpm' | 'python' | 'unknown'
function M.detect_build_system(root)
  root = root or vim.fn.getcwd()
  if vim.fn.filereadable(root .. '/CMakeLists.txt') == 1 then return 'cmake' end
  if vim.fn.filereadable(root .. '/fpm.toml') == 1 then return 'fpm' end
  if vim.fn.filereadable(root .. '/pyproject.toml') == 1
    or vim.fn.filereadable(root .. '/setup.py') == 1 then return 'python' end
  if vim.fn.filereadable(root .. '/Makefile') == 1
    or vim.fn.filereadable(root .. '/makefile') == 1 then return 'make' end
  return 'unknown'
end

---Open a terminal running the project's build command.
---@param root string|nil
function M.build(root)
  root = root or util().find_root(vim.fn.getcwd(),
    { 'CMakeLists.txt', 'Makefile', 'fpm.toml', 'pyproject.toml', '.git' }) or vim.fn.getcwd()
  local system = M.detect_build_system(root)
  local cmd
  if system == 'cmake' then
    -- Configure on first run so `make` has something to do.
    if vim.fn.isdirectory(root .. '/build') == 0 then
      cmd = ('cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && cmake --build build -j'):format()
    else
      cmd = 'cmake --build build -j'
    end
  elseif system == 'make' then
    cmd = 'make -j'
  elseif system == 'fpm' then
    cmd = 'fpm build'
  elseif system == 'python' then
    if vim.fn.filereadable(root .. '/pyproject.toml') == 1 then
      cmd = 'pip install -e . 2>/dev/null || python -m pip install -e .'
    else
      cmd = 'python setup.py build_ext --inplace 2>/dev/null || python setup.py build'
    end
  else
    util().notify('no build system detected in ' .. root, vim.log.levels.WARN)
    return
  end
  M.run_in_terminal(cmd, root)
end

---Open a terminal running the current Python file or the project's test suite.
function M.run_current()
  local ft = vim.bo.filetype
  local path = vim.api.nvim_buf_get_name(0)
  if path == '' then
    util().notify('save the file first', vim.log.levels.WARN)
    return
  end
  local root = util().find_root(vim.fn.fnamemodify(path, ':h'), { '.git', 'pyproject.toml', 'CMakeLists.txt' })
    or vim.fn.getcwd()
  local cmd
  if ft == 'python' then
    cmd = ('python %s'):format(vim.fn.fnameescape(path))
  elseif ft == 'fortran' or ft == 'c' or ft == 'cpp' then
    local out = vim.fn.fnamemodify(path, ':t:r') .. (util().is_windows() and '.exe' or '')
    local compiler
    if ft == 'fortran' then
      compiler = 'gfortran'
    elseif ft == 'c' then
      compiler = 'gcc'
    else
      compiler = 'g++'
    end
    cmd = ('%s %s -o %s && ./%s'):format(compiler, vim.fn.fnameescape(path), out, out)
  else
    cmd = M.detect_build_system(root) ~= 'unknown' and 'make' or 'ls'
  end
  M.run_in_terminal(cmd, root)
end

---Run a shell command in a persisted terminal split.
---@param cmd string
---@param cwd string|nil
function M.run_in_terminal(cmd, cwd)
  local shell = util().is_windows() and { 'pwsh', '-NoLogo', '-Command' } or { 'bash', '-lc' }
  local argv = vim.list_extend({}, shell)
  if util().is_windows() and vim.fn.executable('pwsh') == 0 then
    argv = { 'powershell', '-NoLogo', '-Command' }
  end
  table.insert(argv, cmd)
  vim.cmd('botright 12split')
  local buf = vim.api.nvim_get_current_buf()
  vim.bo[buf].buflisted = false
  local win = vim.api.nvim_get_current_win()
  local ok = pcall(vim.fn.termopen, argv, { cwd = cwd })
  if not ok then
    pcall(vim.fn.jobstart, argv, { cwd = cwd, term = true })
  end
  vim.bo[buf].filetype = 'dshstudio_term'
  vim.api.nvim_set_current_win(win)
  vim.cmd('startinsert')
end

-- ---------------------------------------------------------------------------
-- Setup
-- ---------------------------------------------------------------------------

function M.setup()
  local group = vim.api.nvim_create_augroup('DshStudioLang', { clear = true })

  -- Fortran: correct the filetype, set the form, and keep columns sane.
  vim.api.nvim_create_autocmd('FileType', {
    group = group,
    pattern = 'fortran',
    callback = function(args)
      local form = M.fortran_form(args.buf)
      vim.b[args.buf].dshstudio_fortran_form = form
      if form == 'free' then
        vim.bo[args.buf].expandtab = true
        vim.bo[args.buf].shiftwidth = 2
        vim.bo[args.buf].tabstop = 2
      else
        -- Fixed form is column-sensitive: never expand tabs.
        vim.bo[args.buf].expandtab = false
        vim.bo[args.buf].tabstop = 6
        vim.bo[args.buf].shiftwidth = 6
      end
      -- Fortran keywords are case-insensitive; the built-in syntax file needs
      -- to know it is not a Fortran 77 file to colour free-form continuations.
      vim.b[args.buf].fortran_free_source = (form == 'free') and 1 or 0
      vim.b[args.buf].fortran_fixed_source = (form == 'fixed') and 1 or 0
    end,
  })

  -- Old extensions often land in the wrong filetype.
  vim.api.nvim_create_autocmd({ 'BufReadPost', 'BufNewFile' }, {
    group = group,
    callback = function(args)
      M.fix_fortran_filetype(args.buf)
    end,
  })

  -- Per-language indent and comment conventions.
  local per_lang = {
    c = { tab = 4, expand = true, comment = '// %s' },
    cpp = { tab = 4, expand = true, comment = '// %s' },
    python = { tab = 4, expand = true, comment = '# %s' },
    fortran = { tab = 2, expand = true, comment = '! %s' },
    lua = { tab = 2, expand = true, comment = '-- %s' },
  }
  vim.api.nvim_create_autocmd('FileType', {
    group = group,
    pattern = vim.tbl_keys(per_lang),
    callback = function(args)
      local spec = per_lang[vim.bo[args.buf].filetype]
      if not spec then return end
      vim.bo[args.buf].shiftwidth = spec.tab
      vim.bo[args.buf].softtabstop = spec.tab
      vim.bo[args.buf].tabstop = spec.tab
      vim.bo[args.buf].expandtab = spec.expand
      vim.bo[args.buf].commentstring = spec.comment
      -- Python is whitespace-significant: never let an autoindent guess break it.
      if vim.bo[args.buf].filetype == 'python' then
        vim.bo[args.buf].indentexpr = ''
        vim.bo[args.buf].autoindent = true
        vim.bo[args.buf].smartindent = false
      end
      -- Wrap comments at a sensible width for source files.
      vim.bo[args.buf].textwidth = 100
      vim.bo[args.buf].formatoptions = 'cqj'
    end,
  })

  -- Re-evaluate the Fortran form after a file is written under a new name.
  vim.api.nvim_create_autocmd('BufWritePost', {
    group = group,
    pattern = { '*.f', '*.for', '*.ftn', '*.f90', '*.F90' },
    callback = function(args)
      vim.b[args.buf].dshstudio_fortran_form = M.fortran_form(args.buf)
    end,
  })

  -- Language-specific keymaps, buffer local.
  vim.api.nvim_create_autocmd('FileType', {
    group = group,
    pattern = { 'fortran', 'c', 'cpp', 'python' },
    callback = function(args)
      local opts = { buffer = args.buf, silent = true, desc = 'DSH: build project' }
      vim.keymap.set('n', '<leader>lb', function() M.build() end, opts)
      vim.keymap.set('n', '<leader>lr', function() M.run_current() end,
        { buffer = args.buf, silent = true, desc = 'DSH: run current file' })
      vim.keymap.set('n', '<leader>lc', function()
        M.write_clangd_config(util().find_root(vim.fn.getcwd(), { '.git', 'CMakeLists.txt' }) or vim.fn.getcwd())
      end, { buffer = args.buf, silent = true, desc = 'DSH: write .clangd' })
      vim.keymap.set('n', '<leader>lf', function()
        M.write_fortls_config(util().find_root(vim.fn.getcwd(), { '.git', 'fpm.toml', 'CMakeLists.txt' }) or vim.fn.getcwd())
      end, { buffer = args.buf, silent = true, desc = 'DSH: write .fortls' })
    end,
  })
end

---Report the detected form for the current buffer (statusline / status command).
function M.status()
  if vim.bo.filetype ~= 'fortran' then return '' end
  local form = vim.b.dshstudio_fortran_form or M.fortran_form(0)
  return 'fortran(' .. form .. ')'
end

return M
